export const inventory = [
  {
    id: "DMO-SUV-01",
    year: 2025,
    make: "Orion",
    model: "Vanguard SUV",
    color: "Negro obsidiana",
    kilometers: 8200,
    location: "Ciudad de México",
    price: 795000,
    segment: "SUV ejecutivo",
  },
  {
    id: "DMO-SDN-02",
    year: 2025,
    make: "Aurelia",
    model: "Executive Sedan",
    color: "Gris grafito",
    kilometers: 12500,
    location: "Monterrey",
    price: 645000,
    segment: "Sedán ejecutivo",
  },
  {
    id: "DMO-URB-03",
    year: 2025,
    make: "Atlas",
    model: "Urban Executive",
    color: "Blanco mineral",
    kilometers: 6100,
    location: "Guadalajara",
    price: 485000,
    segment: "Ejecutivo urbano",
  },
  {
    id: "DMO-SUV-04",
    year: 2024,
    make: "Valiant",
    model: "Family SUV",
    color: "Blanco ártico",
    kilometers: 27600,
    location: "Querétaro",
    price: 590000,
    segment: "SUV familiar",
  },
  {
    id: "DMO-SDN-05",
    year: 2025,
    make: "Nova",
    model: "Gran Turismo",
    color: "Azul profundo",
    kilometers: 9800,
    location: "Puebla",
    price: 715000,
    segment: "Sedán premium",
  },
  {
    id: "DMO-FLT-06",
    year: 2025,
    make: "Crest",
    model: "Fleet Executive",
    color: "Plata satinado",
    kilometers: 15700,
    location: "Estado de México",
    price: 525000,
    segment: "Ejecutivo urbano",
  },
];

export const armorPackages = [
  {
    id: "none",
    label: "Sin blindaje",
    level: "Unidad estándar",
    price: 0,
    leadDays: 0,
    note: "Escenario de financiamiento para unidad sin protección adicional.",
  },
  {
    id: "level-iii",
    label: "Blindaje nivel III",
    level: "Protección ejecutiva",
    price: 310000,
    leadDays: 35,
    note: "Parámetro demostrativo. El costo final se valida con el proveedor de blindaje.",
  },
  {
    id: "level-iv",
    label: "Blindaje nivel IV",
    level: "Protección reforzada",
    price: 645000,
    leadDays: 55,
    note: "Parámetro demostrativo. Sujeto a configuración de la unidad y certificación final.",
  },
  {
    id: "level-v",
    label: "Blindaje nivel V",
    level: "Proyecto especializado",
    price: 1100000,
    leadDays: 85,
    note: "Escenario de referencia para una configuración especializada y validación técnica.",
  },
];

export const financingDefaults = {
  annualRate: 17.5,
  openingFeeRate: 2.5,
  insuranceRate: 2.8,
  allowedTerms: [24, 36, 48, 60],
  allowedDownPayments: [20, 25, 30, 35, 40, 50],
};
